import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PDF summarizer",
  description: "Generated by your own pdf now",
};

export default function RootLayout({ children }) {
  const headersList = headers();
  const pathname = headersList.get("next-url");
  return (
    <html lang="en">
      <body className={inter.className}>
        { !pathname.startsWith("/auth") && <Navbar/> }
        {children}
      </body>
    </html>
  );
}
